Emphasize UTF-8 encoding for configs on Windows
sensu/sensu-docs-legacy pull request #549
Opened 2017-03-23 20:07 UTC by gcymbalski

2017-03-23 20:09 UTC, gcymbalski commented
Urgh, Hub isn't respecting my configs. One more try.

2017-03-23 21:46 UTC, cwjohnston commented
My understanding of this issue is that Notepad.exe and possibly other common Windows editors add Byte Order Marking to UTF-8 which we can't parse. Seems to me this is more likely to occur via manual editing instead of programatic generation of JSON.

I think we need to explicitly describe UTF-8 BOM as different from plain UTF-8, and, if possible, link to some reasonably authoritative reference on the matter.

http://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom

2017-03-24 02:09 UTC, cwjohnston requested changes
Closes https://github.com/sensu/sensu/issues/1232

I think this is really close, just one fix needed.

2017-03-24 02:09 UTC, cwjohnston commented on docs/0.28/platforms/sensu-on-microsoft-windows.md
> +[16]: http://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bomhttp://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom
link is doubled up here

2017-03-24 05:16 UTC, gcymbalski commented
Oof, that was dumb. Resolved, thanks!

2017-03-24 15:51 UTC, cwjohnston approved these changes

2017-03-24 15:51 UTC, merged